### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by testgoofy** [EndressHauser-ProcessSolutions/simple-netilion-demo#1]
OAuth Authentication dosn't work.

**Comment by JonasSchultheiss-EH** [comment]
This use case is new for Netilion Connect, as we make client site requests. At the moment all requests to /oauth/token get blocked by the browser because of CORS policies.

I'm currently refactoring the website and made the oauth2 integration today. All thats left is that I can successfully make these requests.

Marco Roth has fixed the bug in the API and it will be deployed to production around Friday.

**Comment by JonasSchultheiss-EH** [comment]
This use case (client side requests) won't be supported by the iiot team.
